#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 28 23:42:03 2018

@author: mson
"""

class 

class Layer:
    def __init__(self, name, W, b, activation, lprev = None, lnext = None):
        """ W: a m-by-n matrix
            b: an m-row column vector 
            activation: the activation function for this node
            name: the name of this node 
            lprev: the layer previous to this layer
            lnext: the layer subsequent to this layer
        """
        self.name = name
        self.W = W
        self.b = b
        self.lprev = lprev
        self.lnext = lnext
    
    def shape(self): return W.shape
    
    def propagate_forward_from(layer):
        """
        Performs forward propagation through this layer. 
        If this is layer n, then the layer argument is layer n - 1.
        """
        
    def propagate_backward_from(layer):
        """
        Performs back propagation through this layer. 
        If this is layer n, then the layer argument is layer n + 1.
        """
        